accounts/urls.py
from django.urls import path,include, re_path
from . import views
from .views import DashboardView
from django.contrib.auth import views as auth_views

app_name = "accounts"
# Create you views here
urlpatterns = [
    # Dashboard Views.
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('dashboard/<int:id>/', DashboardView.as_view(), name="dashboard"),

    # User Authentication.
    path('signup/',views.signup, name="register"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # For selecting surgery.
    path('dashboard/hospital/<slug:slug>/', DashboardView.as_view(), name="dashboard-with-surgery"),
    path('dashboard/surgery/<slug:slug>/', views.surgery, name="surgery"),

    # Delete urls.
    path('dashboard/delete/medicine-item/<int:id>/', views.delete_medicine, name="delete_medicine"),
    path('dashboard/delete/prescription-item/<int:id>/', views.delete_prescription_item, name="delete_prescription_item"),
    path('dashboard/delete/prescription/<int:id>/', views.delete_prescription, name="delete_prescription"),

    # For creating new precriptions.
    path('dashboard/new_prescription//', views.new_prescription, name="new_prescription"),
    path('dashboard/new_prescription/<int:id>/', views.new_prescription, name="new_prescription"),


]

blog/urls.py
from django.urls import path,include
from . import views


app_name = "blog"
# Create you views here
urlpatterns = [
    path('blog_list/',views.blog_list, name="blog_list"),
   
]

health_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import reverse
from django.conf.urls import url
from health_news import views
from .views import  SearchResultsView, HealthNewsDayArchiveView

app_name="health_news"

urlpatterns = [
    # List views
    path('news-list/', views.health_news_list, name='health-news-list'),
    path('<slug:category_slug>/', views.health_news_list, name='health-news-list-by-category'),

    # Detail View
    path('news-detail/<int:id>/', views.health_news_detail, name='health-news-detail'),
    
    # Search View
    path('search-result/', SearchResultsView.as_view(), name="search"),

    path('<int:year>/<str:month>/<int:day>/', HealthNewsDayArchiveView.as_view(), name="health_news_day"),

]   

lingfield/urls.py
from django.contrib import admin
from django.urls import path, include
from health_news.views import health_news_detail


from lingfield import views

app_name="lingfield"

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('blog/', views.blog, name='blog'),
    path('branches/', views.branches, name='branches'),
    path('complaints/', views.complaints, name='complaints'),
    path('contact/', views.contact, name='contact'),
    path('download/', views.download, name='download'),
    path('head-office/', views.head_office, name='head_office'),
    path('leaflets/', views.leaflets, name='leaflets'),
    path('more-info/', views.footer, name='more-info'),
    path('prescriptions/', views.prescriptions, name='prescriptions'),
    path('settings/', views.settings, name='settings'),
    path('services/', views.services, name='services'),

   
]

lingfield_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

from accounts import views
from blog import views
from health_advice import views
from health_news import views
from lingfield import views
from medicines import views
from shopping import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lingfield.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('health-advice/', include('health_advice.urls')),
    path('health-news/', include('health_news.urls')),
    path('medicines/', include('medicines.urls')),
    path('shop/', include('shopping.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import reverse
from django.conf.urls import url
from medicines import views
from .views import MedicineDetailView, MedicineListView, SearchResultsView, CategoryDetailView

app_name="medicines"

urlpatterns = [
    # Detail View
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='medicine-category-detail'),
    path('category/detail/<slug:slug>/', MedicineDetailView.as_view(), name='medicine-detail'),

    # List View
    path('category/', views.medicine_category_list, name='medicine-category-list'),    
    path('medicine-list/<slug:slug>/', MedicineListView.as_view(), name='medicine-list'),

    # Search View
    path('search/', SearchResultsView.as_view(), name="search"),
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from shopping import views
from .views import ShopDetailView, ShopListView, SearchResultsView, CartView, CheckOutView

app_name="shopping"

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('delivery/', views.delivery, name='delivery'),
    path('products/', views.product_list, name='product_list'),
    path('products/<slug:subcategory_slug>/', views.product_list, name='product-list-by-subcategory'),
    path('product-detail/<slug:slug>/', ShopDetailView.as_view(), name='product_detail'),

    path('search-result/', SearchResultsView.as_view(), name='search'),

    path('products/add_to_cart/<slug>', views.add_to_cart, name='add_to_cart'),
    path('products/remove_from_cart/<slug>', views.remove_from_cart, name='remove_from_cart'),
    path('products/remove_single_item_from_cart/<slug>', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
]

lingfield/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

lingfield/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from accounts.forms import UserRegisterForm, UserProfileForm, UpdateForm
from .models import UserInfo, UserAddress
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import (
    authenticate,
    get_user_model

)

#create your forms here

lingfield/views.py
from django.shortcuts import render
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from operator import attrgetter
from django.contrib import messages
# Create your views here.

# ADMIN
# The 404 (page not found) view¶
def handler404(request, exception, template_name='admin/404.html'):
    response = render_to_response(template_name)
    response.status_code = 404
    return response

def handler500(request, exception, template_name='admin/500.html'):
    response = render_to_response(template_name)
    response.status_code = 500
    return response

def index(request):
    return render(request, 'lingfield/index.html')

def about(request):
    return render(request, 'lingfield/about.html')


def blog(request):
    return render(request, 'lingfield/blog.html')

def branches(request):
    return render(request, 'lingfield/branches.html')


def complaints(request):
    return render(request, 'lingfield/complaints.html')

def contact(request):
    return render(request, 'lingfield/contact.html')

def download(request):
    return render(request, 'lingfield/download.html')

def head_office(request):
    return render(request, 'lingfield/head_office.html')

def footer(request):
    return render(request, 'lingfield/footer.html')


def leaflets(request):
    return render(request, 'lingfield/leaflets.html')


def prescriptions(request):
    return render(request, 'lingfield/prescriptions.html')

def register(request):
    return render(request, 'lingfield/register.html')


def services(request):
    return render(request, 'lingfield/services.html')

def settings(request):
    return render(request, 'lingfield/settings.html')

lingfield/templates/lingfield/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Lingfield</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=EB Garamond' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Damion' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=IM Fell DW Pica SC' rel='stylesheet'>

    <!-- Google Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

    {% load static %}
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/main.css' %}">
    
</head>
<body data-barba="wrapper" class="dark-mode">
    <div id="ImpNotice" style="text-align: center;background-color: #182628;color: #F2F2F2;height: 40px;padding: 1px 0 10px 0;">
        
        <div class="container" >
            <p style="font-size: 12px;"><i class="fas fa-info-circle" style="color: #3B945E;"></i> <span style="color:  #3B945E;">IMPORTANT</span> To read the national and local advice about corona virus, please click <span><a href="https://www.gov.uk/coronavirus" target="_blank"  style="color: #3B945E;" role="link">here!</a><a href="javascript:void(0)" class="closebtn" onclick="closeNotice()" style="float:right;text-decoration: none;color:  #3B945E;">&times;</a></span></p >
        </div>
    </div>
    
    <!-- <a href='https://pngtree.com/so/drugs'>drugs png from pngtree.com</a> -->
    <!-- <a href='https://pngtree.com/so/pills'>pills png from pngtree.com</a> -->

    {% include 'lingfield/navbar.html' %}
    <div id="page-container">
       
        {% block content %}
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="background-color: transparent;">&times;</button>
                        {{ message | safe }}
                </div>
            {% endfor %}

        {% endblock content %}
    </div>

<!-- <p class=" fixed-bottom text-left" style="width:35px;writing-mode: vertical-rl;text-orientation: upright;background-color: black;padding: 0.6em;left: 0;"><a href="{% url 'lingfield:more-info' %}" style="color: white;" >footer</a></p> -->
    <div class="container">
        <p class=" fixed-bottom text-center"><a href="{% url 'lingfield:more-info' %}" style="color: #F2F2F2;" >Click to see footer</a></p> 
    </div>


    <!-- <script src="https://unpkg.com/@barba/core"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.3.4/gsap.min.js"></script>
     -->
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>   
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <script src="{% static 'js/index.js' %}"></script>

    <script type="text/javascript">
        function closeNotice() {
        document.getElementById("ImpNotice").style.display = "none";}

        function colorModesLight(x) {
        
        var element = document.body;
        element.classList.toggle("dark-mode");
    }


    gsap.from(".index-page-img", {duration: 3, x: 400,opacity: 0,stagger: 0.1, delay:0.8});


    function contentAnimation() {
        var tl = gsap.timeline();
        tl.from(".animate-this", { duration: 1, y: 30, opacity: 0, stagger: 0.4, delay: 0.2 });
    }

    function aboutAnimation() {
        var tl = gsap.timeline();
        tl.from(".abt-page", { duration: 2, y: 100, opacity: 0, stagger: 0.4, delay: 0.3 });
        tl.from(".abt-images", { duration: 2, y: 100, opacity: 0, stagger: 0.4, delay: 0.5 });
    }

    function serviceAnimation() {
        var tl = gsap.timeline();
        tl.from(".service-head", {duration: 2, x: -30, opacity: 0,stagger: 0.4, delay:0.3});
        tl.from(".service-para-left", {duration: 2, x: -400,opacity: 0,stagger: 0.4, delay:0.3});
        tl.from(".service-para-right", {duration: 2, x: 400,opacity: 0,stagger: 0.4, delay:0.2});

        }
    function delay(n) {
        n = n || 2000;
        return new Promise((done) => {
            setTimeout(() => {
                done();
            }, n);
        });
    }


    barba.init({
        sync: true,

        transitions: [
            {
                async leave(data) {
                    const done = this.async();

                    pageTransition();
                    await delay(1000);
                    done();
                },

                async enter(data) {
                    contentAnimation();
                    aboutAnimation();
                    serviceAnimation();
                },

                async once(data) {
                    contentAnimation();
                    aboutAnimation();
                    serviceAnimation();
                },
            },
        ],
    });



    </script>
</body>
</html>

lingfield/templates/lingfield/branches.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='branches'>

        <div class="container">
            <h1 class="text-center" style="font-size: 80px;">OUR BRANCHES</h1>
            <p class=" text-center" style="margin-top: -1%;">Find our nearest branch to you</p>
        </div>

        <div class="container ">
            <form class="col-lg-6 col-md-12 col-sm-12 offset-lg-3" action="#" method="get" >
                <input name="q" class="form-control mr-sm-2" type="text" placeholder="Enter your postcode ..." aria-label="Search" style="font-family: Garamond;">
            </form>
            
            <div class="text-center mt-2">
                <button class="btn btn-info">BRANCH SERVICES</button>
            </div>
        </div>

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2315.6048742632825!2d-1.5115091841168802!3d54.52282948024245!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487e9b47b18b8489%3A0xe1be8033a273fee1!2sLingfield%20Pharmacy!5e0!3m2!1sen!2sng!4v1602355399931!5m2!1sen!2sng" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>    </main>
        <button class="btn btn-lg btn-block btn-info text-right mt-n2">GET DIRECTIONS</button>
        
        <div class="container mt-5">
            <h2>BRANCHES</h2>
            <form class="d-inline w-100" action="#" method="get" >
                <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search" style="font-family: Garamond;">
            </form>
            <div class="container mt-3 rounded" style="background-color: lightgray;">
                <a href="{% url 'lingfield:about' %}" style="color: black;text-decoration: none;">
                   <div class="ml-3 mt-3">
                        <h6 >LINGFIELD PHARMACY</h6>
                        <div >
                            <address>Unit 34, Flexspace, Lingfield Way<br>Darlington<br>Durham<br>DLI 4QZ</address>
                        </div>
                        <div class="row">
                            <div class="col-1">
                                <i class="material-icons mr-n5">call</i>
                            </div>
                            <div class="col-7">
                                <p><a href="tel:01325790026" style="text-decoration: underline;color: black;">01325 790026</a></p>
                            </div>
                        </div>
                   </div>
                </a>
            </div>
        </div>

        
    </main>
</div>

{% endblock content %}

lingfield/templates/lingfield/head_office.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='complaints'>
        <div class="container">
            <h1 class="col-12 text-center each-page-header" style="font-family: IM Fell DW Pica SC;">HEAD OFFICE</h1>
        </div>

        <div class="container">
            <p>Our hard working team provide a first class service to all our patients. Lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet.</p>
            <div >
                <p><a href="tel:01325790026" style="text-decoration: underline;color: black;">01325 790026</a></p>
            </div>
        </div> 
    </main>
</div>
{% endblock content %}

lingfield/templates/lingfield/index.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='home'>

       <div class="container">
           
            <div class="index-page-text" style="margin-top: 40px;">
                <div class="col-12">
                    <img class="index-page-img" src="{% static 'images//pharmacy/Pharmacist/3725269.jpg' %}" width="100%" height="380px" style="object-fit: contain;margin-left: 23%;">
                    <br>
                    <div style="position: relative;width: 100%;" class="col-12 animate-this">
                        <h1 class="home-page-header text-lg-left text-sm-center" style="width: 100%;font-family: IM Fell DW Pica SC;line-height: 90%;color: #116466;text-shadow: 0px 15px 5px rgba(0,0,0,0.1),10px 20px 5px rgba(0,0,0,0.1),-10px 20px 5px rgba(0,0,0,0.1);">
                    Lingfield <br> Pharmacy
                        <!-- <span>L</span><span>i</span><span>n</span><span>g</span><span>f</span><span>i</span><span>e</span><span>l</span><span>d</span>
                        <br> 
                        <b><span>P</span><span>h</span><span>a</span><span>r</span><span>m</span><span>a</span><span>c</span><span>y</span> </b> -->
                    </h1>  
                    <p class="mt-4" style="color: #182628;text-shadow: 0px 15px 5px rgba(0,0,0,0.1),10px 20px 5px rgba(0,0,0,0.1),-10px 20px 5px rgba(0,0,0,0.1);">We are an independent NHS Community Pharmacy serving the <br> people of Darlington.</p>
                    <div class="animate-this pres-button mt-4">
                        {% if user.is_authenticated %}
                            <a href="{% url 'accounts:dashboard' %}" >place order</a>
                        {% else %}
                            <a href="{% url 'lingfield:prescriptions' %}">place order</a>
                        {% endif %}
                    </div>
                    </div>
                    
                </div>
                <!-- <img class="index-page-img" src="{% static 'images//pharmacy/Pharmacist/3725269.jpg' %}" height="450px" style="object-fit: cover;"> -->

                    <!-- <img class="index-page-img" src="{% static 'images//pharmacy/Pharmacist/3725269.jpg' %}" height="450px" style="object-fit: cover;"> -->
            </div>

            <!-- <div class="home-page-images" >
                <h1 class="welcome  home-page-header" style="position: absolute; top: 50%; left: 50%;transform: translate(-50%, -50%);width: 100%;font-family: IM Fell DW Pica SC;">
                    Welcome to <br>
                    <span style="text-decoration: none;">
                        <a href="{% url 'lingfield:leaflets' %}" style="text-decoration: underline;color: #182628;" data-toggle="tooltip" data-placement="top" title="leaflets">L</a><a href="{% url 'lingfield:home' %}" style="text-decoration: underline;color: #212529;;" title="home">i</a>ngfiel{% if user.is_authenticated %}<a href="{% url 'accounts:dashboard'%}" style="text-decoration: underline;color: #212529;" title="dashboard">d</a>{% else %}<a href="#" style="text-decoration: underline;color: #212529;">d</a>{% endif %}
                        <a href="{% url 'lingfield:prescriptions' %}" style="text-decoration: underline;color: #212529;;" title="prescriptions">P</a><a href="{% url 'health_advice:health-advice-category-list' %}" style="text-decoration: underline;color: #212529;;" title="health-advice">h</a><a href="{% url 'lingfield:about' %}" style="text-decoration: underline;color: #212529;;" title="about">a</a>{% if user.is_authenticated %}<a href="#" style="text-decoration: underline;color: #212529;;">r</a>{% else %}<a href="{% url 'accounts:register' %}" style="text-decoration: underline;color: #212529;;">r</a>{% endif %}<a href="{% url 'medicines:medicine-category-list'%}" style="text-decoration: underline;color: #212529;;" title="medicine">m</a>a<a href="{% url 'lingfield:contact' %}" style="text-decoration: underline;color: #212529;;" title="contact">c</a>y 
                    </span>
                </h1>  
            </div>   -->
            <!-- <img src="{% static 'images\_____simplelife.m-___CEoV9j-A-Rr___-.jpg' %}" width="60%" height="500px" style="object-fit: cover; position: absolute; border-radius:70% 30% 30% 70% / 60% 40% 60% 40%;"> -->

                        
        </div>
    </main>
</div>

<script type="text/javascript">
   
</script>
{% endblock content %}

lingfield/templates/lingfield/navbar.html
{% load static %}
<header class="sticky-top" style="box-shadow: 0px 10px 8px rgba(0,0,0,0.1);">
    <nav style="margin: auto;" >
        <div class="row">
            <span class="animate-this text-left col-lg-4 col-md-4 col-sm-4" style="float: left;color: #182628;"><h3><a href="{% url 'lingfield:home' %}" style="color: #182628;text-decoration: none;font-family: Damion;">+LingField</a></h3></span>
            <div class="text-center col-lg-4 col-md-4 col-sm-4">
                {% if user.is_authenticated %}
                <span class="animate-this mr-2" ><a class="cart-icon" href="{% url 'shopping:cart' %}" style="color: #182628; font-family:IM Fell DW Pica SC;" data-toggle="tooltip" data-placement="right"> Cart</a></span>
                <span class="animate-this" style="border-right: 1px solid #182628;"></span>
                {% else %}
                <span></span>
                {% endif %}
                {% if user.is_authenticated %}
                <span class="animate-this ml-2" ><a href="{% url 'accounts:dashboard' %}" style="color: #182628; font-family:IM Fell DW Pica SC;" data-toggle="tooltip" data-placement="right">Dashboard</a></span>
                <span class="animate-this ml-2" style="border-right: 1px solid #182628;"></span>
                {% else %}
                <span></span>
                {% endif %}
                {% if user.is_authenticated %}
                <span class="animate-this ml-2"><a href="{% url 'logout' %}?next=/" style="color: #182628; font-family:IM Fell DW Pica SC;" data-toggle="tooltip" data-placement="right">Logout</a></span>
                {% else %}
                <span class="animate-this"><a href="{% url 'accounts:register' %}" style="color: #182628; font-family:IM Fell DW Pica SC;" data-toggle="tooltip" data-placement="right"> Register</a></span>
                <span class="animate-this ml-2" style="border-right: 1px solid #182628;"></span>
                <span class="animate-this ml-2"><a href="{% url 'login' %}" style="color: #182628; font-family:IM Fell DW Pica SC;" data-toggle="tooltip" data-placement="right"> Login</a></span>
                {% endif %}
            </div>

            <span class="col-lg-4 col-md-4 col-sm-4 text-right" style="float: right;">
                <div class="all-nav oneline dropdown">
                    <span id="disNav" class="dropbtn animate-this" style="color: #182628;cursor: pointer;font-family:IM Fell DW Pica SC;" onclick="openNaviGate()">All Menu</span>
                <div id="NaviGate" class="navigate">
                    <nav>
                        <ul>
                            <div class="dropdown-content">
                                <a href="{% url 'lingfield:home'%}">Home</a>
                                <a href="{% url 'lingfield:about'%}">About</a>
                                <a href="{% url 'blog:blog_list'%}">Blogs</a>
                                <a href="{% url 'lingfield:complaints'%}">Complaints</a>
                                <a href="{% url 'lingfield:contact' %}">Contact</a>
                                {% if user.is_authenticated %}
                                <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
                                {% else %}
                               
                                {% endif %}
                                <a href="{% url 'lingfield:download'%}" class="download-nav" style="font-size: 18px;">Download Our App</a>
                                <a href="{% url 'health_advice:health-advice-category-list' %}">Health Advice</a>
                                <a href="{% url 'health_news:health-news-list'  %}">Health News</a>
                                <a href="{% url 'lingfield:leaflets'%}">Leaflets</a>
                                <a href="{% url 'medicines:medicine-category-list'%}">Medicine A-Z</a>
                                {% if user.is_authenticated %}
                                <a href="{% url 'accounts:dashboard' %}">Prescriptions</a>
                                {% else %}
                                <a href="{% url 'lingfield:prescriptions'%}">Prescriptions</a>
                                {% endif %}
                                {% if user.is_authenticated %}
                                
                                {% else %}
                                <a href="{% url 'accounts:register'%}">Register</a>
                                {% endif %}
                                <a href="{% url 'lingfield:services'%}">Services</a>
                                <a href="{% url 'lingfield:settings'%}">Settings</a>
                                <a href="{% url 'shopping:product_list'%}" class="mb-3">Shopping</a>
                                </div>    
                        </ul>
                    </nav>
                </div>
                </div></span>
        </div>
    </nav>
</header>

<script type="text/javascript">

    var allnav = document.getElementById("disNav");

    allnav.onclick = function openNaviGate() {
        var div = document.getElementById("NaviGate");
        if (div.style.display !== 'none') {
            div.style.display = 'none';
            document.getElementById("disNav").textContent = "All Menu";
            document.g
            etElementById("NaviGate").style.width = "350px";
        }
        else {
            div.style.display = 'block';
            document.getElementById("disNav").textContent = "Close";
            document.getElementById("NaviGate").style.width = "0";
        }
    };

    function colorModesLight(x) {
        x.classList.toggle("fa-sun");
        
    }

    window.onscroll = function() {myFunction()};

    var header = document.getElementById("myHeader");
    var sticky = header.offsetTop;

    function myFunction() {
        if (window.pageYOffset > sticky) {
            header.classList.add("sticky");
        } else {
            header.classList.remove("sticky");
        }
    }

</script>