blog/urls.py
from django.urls import path,include
from . import views


app_name = "blog"
# Create you views here
urlpatterns = [
    path('blog_list/',views.blog_list, name="blog_list"),
   
]

health_advice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import reverse
from django.conf.urls import url
from health_advice import views
from .models import HealthAdvice
from .views import HealthAdviceDetailView, HealthAdviceListView, SearchResultsView, CategoryDetailView

app_name="health_advice"

urlpatterns = [
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='health-advice-category-detail'),
    path('category/', views.health_advice_category_list, name='health-advice-category-list'),
    
    path('category/detail/<slug:slug>/', HealthAdviceDetailView.as_view(),  name='health-advice-detail'),
    
    path('search/', SearchResultsView.as_view(), name="search"),
]

lingfield_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

from accounts import views
from blog import views
from health_advice import views
from health_news import views
from lingfield import views
from medicines import views
from shopping import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lingfield.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('health-advice/', include('health_advice.urls')),
    path('health-news/', include('health_news.urls')),
    path('medicines/', include('medicines.urls')),
    path('shop/', include('shopping.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

health_advice/models.py
from django.db import models
from django.shortcuts import reverse
from djrichtextfield.models import RichTextField

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=20,unique=False)
    slug = models.SlugField(unique=False)
   
    class Meta():
        ordering = ['title']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories' #a,b,c,d...

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("health_advice:health-advice-list", kwargs={
            'slug' : self.slug
        })

  
    
class HealthAdvice(models.Model):
    category = models.ForeignKey(Category, verbose_name="Category",on_delete=models.CASCADE)
    title = models.CharField(max_length=1000,unique=False)
    list_description = models.CharField(max_length=1000)
    detail_description =  models.TextField(max_length=100000000)
    slug = models.SlugField()

    class Meta():
        ordering = ['title']
        verbose_name = 'Health Advice'
        verbose_name_plural = 'Health Advices' #a,b,c,d...

    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("health_advice:health-advice-detail", kwargs={
            'slug' : self.slug
        })

health_advice/views.py
from django.shortcuts import render,get_object_or_404
from .models import HealthAdvice, Category
from django.views.generic import View, ListView, DetailView
from django.views.generic.list import MultipleObjectMixin
from django.db.models import Q

# Create your views here.
class HealthAdviceDetailView(DetailView):
    model = HealthAdvice
    template_name = "health_advice/health-advice-detail.html"

    def get_context_data(self, *args, **kwargs):
        # Get all details of a specific category(A, B, C, E...) when clicked and returns it.
        context = super(HealthAdviceDetailView, self).get_context_data(*args, **kwargs)
        context['health_advice_list'] = Category.objects.all()
        return context

class HealthAdviceListView(ListView):
    model = HealthAdvice
    template_name = "health_advice/health-advice-list.html"
    
class CategoryListView(ListView):
    # List all the categories.
    model = HealthAdvice
    template_name = "health_advice/health-advice-category-list.html"
    

class SearchResultsView(ListView):
    model = HealthAdvice
    template_name = 'health_advice/search.html'
   
    def get_queryset(self): # new
        query = self.request.GET.get('q_health_advice')
        object_list = HealthAdvice.objects.filter(
            Q(title__icontains=query) 
        )
        return object_list

class CategoryDetailView(DetailView,MultipleObjectMixin):
    model = Category
    template_name = "health_advice/Health-advice-category-detail.html"

    def get_context_data(self, **kwargs):
        object_list = HealthAdvice.objects.filter(category=self.get_object())
        context = super(CategoryDetailView, self).get_context_data(object_list=object_list, **kwargs)
        return context
 
# ----------------- HEALTH ADVICE   -----------------------#
def health_advice_category_list(request):
    context = {'categories':Category.objects.all()}
    return render(request, 'health_advice/health-advice-category-list.html', context)

def health_advice_category_detail(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    healthadvices = HealthAdvice.objects.filter(category__slug=category_slug)
    context = {'category':category,'healthadvices': healthadvices}
    return render(request, 'health_advice/health-advice-category-detail.html', context)


def health_advice_list(request):
    healthadvices = get_object_or_404(HealthAdvice).order_by('categories')
    context = {'healthadvices': healthadvices}
    return render(request, 'health_advice/health-advice-list.html', context)

def health_advice_detail(request,pk):
    categories = Category.objects.filter()
    healthadvices = get_object_or_404(HealthAdvice, pk=pk)
    return render(request, 'health_advice/health-advice-detail.html', {'healthadvices':healthadvices, 'categories':categories})

health_advice/templates/health_advice/health-advice-category-detail.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %} 
    <div class="wrapper">
        <main data-barba="container" data-barba-namespace='healthadvice-category-detail'>
            <div class="container">
                <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">HEALTH A-Z</h1>
                <p class="text-center mt-n3" style="color: #3B945E;">Browse conditions, medicines and health advice</p>
                
                <form class="d-inline w-100" action="{% url 'health_advice:search' %}" method="get">
                    <input name="q_health_advice" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;background-color:#65CCB8;color: #3B945E;border: none;border-bottom: 1px solid #2C3531;">
                  </form>
            </div>
    
            <div class="container mt-5" style="color:#182628;">
                    {% for healthadvice in category.healthadvice_set.all %}
                        <a class="category-detail" href="{{ healthadvice.get_absolute_url }}"  style="text-decoration: none;color: #212529;">
                            <h4><strong>{{ healthadvice.title }}</strong></h4>
                            <p style="color:#3e6b72;">{{ healthadvice.list_description }}
                            </p>
                            <hr class="featurette-divider">
                        </a> 
                    {% empty %}
                        <h1 class="text-center mt-n4" style="font-size: 100px;color: #3B945E;">Oops!!!</h1>
                        <h5 class="text-center"><b>No advice available here.</b></h5>
                        <div class="text-center">
                            <button class="btn btn-hover" type="submit"><a  data-fancybox-close="" href="{% url 'health_advice:health-advice-category-list' %}" style="text-decoration: none;color: #F2F2F2;">GO TO HEALTH ADVICE LIST</a></button>
                        </div>  
                    {% endfor %}
                </div>
            </div>      
        </main>
    </div>   

<div class="container">
    <p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>
</div>     

{% endblock content %}

health_advice/templates/health_advice/health-advice-category-list.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='health-advice-category-list'>
      <div class="container">
        <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">HEALTH A-Z</h1>
        <p class="text-center mt-n3" style="color: #3B945E;">Browse conditions, medicines and health advice</p>
            
        <form class="d-inline w-100 mt-4" action="{% url 'health_advice:search' %}" method="get">
          <input name="q_health_advice" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;background-color:#65CCB8;color: #3B945E;border: none;border-bottom: 1px solid #2C3531;">
        </form>
      </div>
      <div class="container">
        <div class="health-advice-list">
            <ul  style="text-align: justify;text-justify: inter-word;">
              {% for category in categories %}
              <li class="mr-3 mr-lg-5" ><a href="{% url 'health_advice:health-advice-category-detail' category.slug %}">{{ category.title }}</a></li>
              {% endfor %}
            </ul>
        </div>
      </div>
    </main>
</div>

{% endblock content %}

health_advice/templates/health_advice/health-advice-detail.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='health-advice-detail'>
        <div class="container">
            <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">{{ object.title }}</h1>
            <p class="text-center mt-n3" style="color: #3B945E;">Health Advice</p>
            
            <form class="d-inline w-100" action="{% url 'health_advice:search' %}" method="get">
                <input name="q_health_advice" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;background-color:#65CCB8;color: #3B945E;border: none;border-bottom: 1px solid #2C3531;">
                <!-- <button class="btn btn-outline-dark my-2 my-sm-0 text-white" type="submit" style="font-family: Garamond;">Search</button> -->
              </form>
        </div>

        <div class="container mt-5">
            <p style="text-align: justify;text-justify: inter-word;">
                {{ object.detail_description }}
            </p>
        </div>
    </main>
</div>

<p class="text-right fixed-bottom"><a href="#" style="border: 10px solid teal;background-color: teal;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>


{% endblock content %}

health_advice/templates/health_advice/health-advice-list.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='health-advice-list'>
        <div class="container">
            <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">HEALTH A-Z</h1>
            <p class="text-center">Browse conditions, medicines and health advice</p>
            
            <form class="d-inline w-100" action="{% url 'health_advice:search' %}" method="get">
                <input name="q_health_advice" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;">
            </form>
        </div>

        <div class="container mt-5">
            <div>
                {% for healthadvice in healthadvice_list %}
                    <a href="{{ healthadvice.get_absolute_url }}"  style="text-decoration: none;color: #212529;">
                        <h4>{{ healthadvice.title }}</h4>
                        <p>{{ healthadvice.list_description }}
                        </p>
                        <hr class="featurette-divider">
                    </a>               
                {% endfor %}
            </div>
        </div>      
    </main>
</div>

<div class="container">
    <p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>
</div>
{% endblock content %}

health_advice/templates/health_advice/search.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='search'>
        <div class="container">
            <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">HEALTH A-Z</h1>
            <p class="text-center">Browse conditions, medicines and health advice</p>
            
        </div>

        <div class="container mt-5">
            <div>
                {% for healthadvice in object_list %}
                    
                        <a href="{{ healthadvice.get_absolute_url }}"  style="text-decoration: none;color: #212529;">
                            <h4>{{ healthadvice.title }}</h4>
                            <p>{{ healthadvice.list_description }}
                            </p>
                        </a> 
                        <hr class="featurette-divider">
                    {% empty %}
                        <h1 class="text-center mt-n4" style="font-size: 100px;color: #3B945E">Oops!!!</h1>
                        <h5 class="text-center"><b>No advice available here.</b></h5>
                        <div class="text-center">
                            <button class="btn btn-hover" type="submit"><a  data-fancybox-close="" href="{% url 'health_advice:health-advice-category-list' %}" style="text-decoration: none;color: white;">GO TO HEALTH ADVICE LIST</a></button>
                        </div> 
                {% endfor %}
            </div>
            <div>
               
            </div>
        </div>      
    </main>
</div>

<p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>
{% endblock content %}