blog/urls.py
from django.urls import path,include
from . import views


app_name = "blog"
# Create you views here
urlpatterns = [
    path('blog_list/',views.blog_list, name="blog_list"),
   
]

lingfield_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

from accounts import views
from blog import views
from health_advice import views
from health_news import views
from lingfield import views
from medicines import views
from shopping import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lingfield.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('health-advice/', include('health_advice.urls')),
    path('health-news/', include('health_news.urls')),
    path('medicines/', include('medicines.urls')),
    path('shop/', include('shopping.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import reverse
from django.conf.urls import url
from medicines import views
from .views import MedicineDetailView, MedicineListView, SearchResultsView, CategoryDetailView

app_name="medicines"

urlpatterns = [
    # Detail View
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='medicine-category-detail'),
    path('category/detail/<slug:slug>/', MedicineDetailView.as_view(), name='medicine-detail'),

    # List View
    path('category/', views.medicine_category_list, name='medicine-category-list'),    
    path('medicine-list/<slug:slug>/', MedicineListView.as_view(), name='medicine-list'),

    # Search View
    path('search/', SearchResultsView.as_view(), name="search"),
]

medicines/models.py
from django.db import models
from django.shortcuts import reverse
from djrichtextfield.models import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=20,unique=False)
    slug = models.SlugField()

    class Meta():
        ordering = ['title']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories' #a,b,c,d...

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("medicines:medicine-category-detail", kwargs={
            'slug' : self.slug
        })


class Medicine(models.Model):
    category = models.ForeignKey(Category, verbose_name="Category",on_delete=models.CASCADE)
    title = models.CharField(max_length=1000,unique=False)
    list_description = models.CharField(max_length=1000)
    detail_description =  models.TextField(max_length=1000000)
    slug = models.SlugField()

    class Meta():
        ordering = ['title']
        verbose_name = 'Medicine'
        verbose_name_plural = 'Medicines' #a,b,c,d...

    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("medicines:medicine-detail", kwargs={
            'slug' : self.slug
        })

    def get_medicine_url(self):
        return reverse("accounts:item", kwargs={
            'slug' : self.slug
        })

medicines/views.py
from django.shortcuts import render
from .models import  Category, Medicine
from django.views.generic import View, ListView, DetailView
from django.views.generic.list import MultipleObjectMixin
from django.db.models import Q

# Create your views here.
class MedicineDetailView(DetailView):
    model = Medicine
    template_name = "medicines/medicine-detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(MedicineDetailView, self).get_context_data(*args, **kwargs)
        context['medicine_list'] = Category.objects.all()
        return context

class MedicineListView(ListView):
    model = Medicine
    template_name = "medicines/medicine-list.html"


class SearchResultsView(ListView):
    model = Medicine
    template_name = 'medicines/search.html'
   
    def get_queryset(self): # new
        query = self.request.GET.get('q_medicines')
        object_list = Medicine.objects.filter(
            Q(title__icontains=query) 
        )
        return object_list

class CategoryDetailView(DetailView,MultipleObjectMixin):
    model = Category
    template_name = "medicines/medicine-category-detail.html"

    def get_context_data(self, **kwargs):
        object_list = Medicine.objects.filter(category=self.get_object())
        context = super(CategoryDetailView, self).get_context_data(object_list=object_list, **kwargs)
        return context
 

def medicine_category_list(request):
    context = {'categories':Category.objects.all()}
    return render(request, 'medicines/medicine-category-list.html',context)

medicines/templates/medicines/medicine-category-detail.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="wrapper">
        <main data-barba="container" data-barba-namespace='medicines-category-detail'>
            <div class="container">
                <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">MEDICINES A-Z</h1>
                <p class="text-center">Browse medicines</p>
                
                <form class="d-inline w-100" action="{% url 'medicines:search' %}" method="get">
                    <input name="q_medicines" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;background-color:#65CCB8;color: #3B945E;border: none;border-bottom: 1px solid #2C3531;">
                    <!-- <button class="btn btn-outline-dark my-2 my-sm-0 text-white" type="submit" style="font-family: Garamond;">Search</button> -->
                  </form>
            </div>
    
            <div class="container mt-5">
                <div>
                    {% for medicine in category.medicine_set.all %}
                        <a class="category-detail" href="{{ medicine.get_absolute_url }}"  style="text-decoration: none;color: #212529;">
                            <h4><strong>{{ medicine.title }}</strong></h4>
                            <p style="color:#3e6b72;">{{ medicine.list_description }}
                            </p>
                            <hr class="featurette-divider">
                        </a> 
                    {% empty %}
                        <h1 class="text-center mt-n4" style="font-size: 100px;color: #3B945E;">Oops!!!</h1>
                        <h5 class="text-center"><b>No medicine available here..</b></h5>
                        <div class="text-center">
                            <button class="btn btn-hover" type="submit"><a  data-fancybox-close="" href="{% url 'medicines:medicine-category-list' %}" style="text-decoration: none;color: white;">GO TO MEDICINE LIST</a></button>
                        </div>  
                    {% endfor %}
                </div>
            </div>      
        </main>
    </div>   

    
    <p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>

       
{% endblock content %}

medicines/templates/medicines/medicine-category-list.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='medicine-category-list'>
      <div class="container">
        <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">MEDICINES A-Z</h1>
        <p class="text-center">Browse medicines</p>
        
        <form class="d-inline w-100" action="{% url 'medicines:search' %}" method="get">
            <input name="q_medicines" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;background-color:#65CCB8;color: #3B945E;border: none;border-bottom: 1px solid #2C3531;">
        </form>
      </div>
      <div class="container">
        <div class="health-advice-list">
            <ul style="text-align: justify;text-justify: inter-word;">
                {% for category in categories %}
                <li class="mr-3 mr-lg-5"><a href="{% url 'medicines:medicine-category-detail' category.slug %}">{{ category.title }}</a></li>
                {% endfor %}

            </ul>
        </div>
      </div>
    </main>
</div>

{% endblock content %}

medicines/templates/medicines/medicine-detail.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='medicine-detail'>  
        <div class="container">
            <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">{{ object.title }}</h1>
            <p class="text-center">Medicine Information</p>
            
            <form class="d-inline w-100" action="{% url 'medicines:search' %}" method="get">
                <input name="q_medicines" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;background-color:#65CCB8;color: #3B945E;border: none;border-bottom: 1px solid #2C3531;">
            </form>
        </div>

        <div class="container mt-5">
            <p style="text-align: justify;text-justify: inter-word;">
                {{ object.detail_description }}
            </p>
        </div>

    </main>
</div>
<p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>

{% endblock content %}

medicines/templates/medicines/medicine-list.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='medicine-list'>
        <div class="container">
            <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">MEDICINES A-Z</h1>
            <p class="text-center">Browse medicines</p>
            
            <form class="d-inline w-100" action="{% url 'medicine:search' %}" method="get">
                <input name="q_medicine" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" style="font-family: Garamond;">
            </form>
        </div>

        <div class="container mt-5">
            <div>
                {% for medicine in object_list %}
                    <a href="{{ medicine.get_absolute_url }}"  style="text-decoration: none;color: #212529;">
                        <h4>{{ medicine.title }}</h4>
                        <p>{{ medicine.list_description }}
                        </p>
                        <hr class="featurette-divider">
                    </a>               
                {% endfor %}
            </div>
        </div> 
    </main>
</div>

<div class="container">
    <p class="text-right fixed-bottom "><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>
</div>
{% endblock content %}

medicines/templates/medicines/search.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="wrapper">
    <main data-barba="container" data-barba-namespace='search'>
        <div class="container">
            <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">MEDICINES A-Z</h1>
            <p class="text-center">Browse medicines</p>
        </div>

        <div class="container mt-5">
            <div>
                {% for medicine in object_list %}
                        <a href="{{ medicine.get_absolute_url }}"  style="text-decoration: none;color: #212529;">
                            <h4>{{ medicine.title }}</h4>
                            <p>{{ medicine.list_description }}
                            </p>
                        </a> 
                        <hr class="featurette-divider">
                    {% empty %}
                        <h1 class="text-center mt-n4" style="font-size: 100px;color: #3B945E">Oops!!!</h1>
                        <h5 class="text-center"><b>No medicine available here.</b></h5>
                        <div class="text-center">
                            <button class="btn btn-hover" type="submit"><a  data-fancybox-close="" href="{% url 'medicines:medicine-category-list' %}" style="text-decoration: none;color: white;">GO TO MEDICINE LIST</a></button>
                        </div>                       
                {% endfor %}
            </div>
        </div>      
    </main>
</div>

<p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #5fbae9;background-color: #5fbae9;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>
{% endblock content %}