blog/urls.py
from django.urls import path,include
from . import views


app_name = "blog"
# Create you views here
urlpatterns = [
    path('blog_list/',views.blog_list, name="blog_list"),
   
]

lingfield_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

from accounts import views
from blog import views
from health_advice import views
from health_news import views
from lingfield import views
from medicines import views
from shopping import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lingfield.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('health-advice/', include('health_advice.urls')),
    path('health-news/', include('health_news.urls')),
    path('medicines/', include('medicines.urls')),
    path('shop/', include('shopping.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from shopping import views
from .views import ShopDetailView, ShopListView, SearchResultsView, CartView, CheckOutView

app_name="shopping"

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('delivery/', views.delivery, name='delivery'),
    path('products/', views.product_list, name='product_list'),
    path('products/<slug:subcategory_slug>/', views.product_list, name='product-list-by-subcategory'),
    path('product-detail/<slug:slug>/', ShopDetailView.as_view(), name='product_detail'),

    path('search-result/', SearchResultsView.as_view(), name='search'),

    path('products/add_to_cart/<slug>', views.add_to_cart, name='add_to_cart'),
    path('products/remove_from_cart/<slug>', views.remove_from_cart, name='remove_from_cart'),
    path('products/remove_single_item_from_cart/<slug>', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
]

shopping/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from djrichtextfield.models import RichTextField
from django.utils import timezone

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    date_paid = models.DateTimeField(auto_now_add=True)
    
class Category(models.Model):
    title = models.CharField(max_length=50,unique=False)
    slug = models.SlugField(max_length=1000, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta():
        ordering = ['title']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories' #a,b,c,d...

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shopping:product-list-by-category", args=[self.slug])

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=1000, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta():
        ordering = ['title']
        verbose_name = 'Subcategory'
        verbose_name_plural = 'Subcategories' #a,b,c,d...

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shopping:product-list-by-subcategory",args=[self.slug])


class Shop(models.Model):
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE,related_name='shops',)
    title = models.CharField(max_length=1000,unique=False)
    image = models.ImageField(upload_to='shop_products')
    price = models.FloatField()
    old_price = models.FloatField(blank=True, null=True)
    first_description = models.TextField(max_length=1000000)
    second_description =  models.TextField(max_length=1000000)
    directions =  models.TextField(max_length=1000000)
    warnings =  models.TextField(max_length=1000000)
    ingredients =  models.TextField(max_length=1000000)
    slug = models.SlugField()
    total_excl_vat = models.FloatField()
    vat = models.FloatField()
    shipping_cost = models.FloatField()

    class Meta():
        ordering = ['title']
        verbose_name = 'Shop'
        verbose_name_plural = 'Shops' #a,b,c,d...

    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shopping:product_detail", kwargs={
            'slug' : self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("shopping:add_to_cart", kwargs={
            'slug' : self.slug
        })
    
    def get_remove_from_cart_url(self):
        return reverse("shopping:remove_from_cart", kwargs={
            'slug' : self.slug
        })

class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item =  models.ForeignKey(Shop, on_delete=models.CASCADE)
    item_quantity = models.IntegerField(default=1, null=True, blank=True)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return "{} of {}".format(self.item_quantity,self.item.title)
        
    def get_total_items_price(self):
        return self.item_quantity * self.item.price 

    def get_total_items_price_with_excl_vat(self):
        return self.item_quantity  * self.item.total_excl_vat

    def get_total_items_price_with_vat(self):
        return self.item_quantity  * self.item.vat

    def get_total_items_price_with_shipping_cost(self):
        return self.item_quantity  * self.item.shipping_cost

    def get_total_discount_items_price(self):
        return self.item_quantity * self.item.old_price

    def get_amount_saved(self):
        return self.get_total_items_price() - self.get_total_discount_items_price()

    def get_price_total(self):
        return self.get_total_items_price() 

    def get_grand_price_total(self):
        return self.get_total_items_price() + self.get_total_items_price_with_shipping_cost() + self.get_total_items_price_with_vat() + self.get_total_items_price_with_excl_vat()
        + self.get_total_discount_items_price()

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_price_total() 
        return total
    
    def get_grand_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_grand_price_total() 
        return total

    def get_total_discount(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_amount_saved()
        return total

    def get_total_excl_vat(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_items_price_with_excl_vat() 
        return total

    def get_total_vat(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_items_price_with_vat()
        return total
    
    def get_total_shopping_cost(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_items_price_with_shipping_cost()
        return total

    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for items in orderitems])
        return total

    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.item_quantity for items in orderitems])
        return total

shopping/forms.py
from django import forms
from .models import *
from accounts.forms import *
from accounts.models import *
from crispy_forms.helper import FormHelper
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation
from django.contrib.auth import (
    authenticate,
    get_user_model

)
from django_countries.fields import CountryField


PAYMENT_CHOICES = (
    ('Credit', 'Credit'),
    ('Debit', 'Debit'),
    ('Paypal', 'Paypal')
)


class CheckOutDelivery(forms.ModelForm):
    payment = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

    class Meta():
        model = Order
        fields = '__all__'


class PaymentForm(forms.ModelForm):
    name_on_card = forms.CharField()
    credit_card_number = forms.CharField()
    expiration = forms.CharField()
    cvv = forms.CharField()

    class Meta():
        model = Payment
        fields = {'name_on_card','credit_card_number','expiration','cvv'};    

    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args,**kwargs)
        self.fields['cvv'].label = "CVV"

shopping/templates/shopping/cart.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="wrapper">
    <main data-barba="container" data-barba-namespace='cart'>
        <div class="container mt-3">
            <div class="row">
                <div class="col-lg-9 col-md-12 col-sm-12">
                    <h4 class="text-left" style="font-family: IM Fell DW Pica SC;"><u>{{ user.username }}'s  Cart</u></h4>
                </div>              
            </div>
        </div>
            <br>

        <!-- Start Cart  -->
            <div class="cart-box-main">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="container">
                                <div class="col-lg-6 offset-lg-3">
                                     {% for message in messages %}
                                     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="background-color: transparent;">&times;</button>
                                         {{ message | safe }}
                                     </div>
                                     {% endfor %}
                                </div>
                             </div>
                            <div class="table-main table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th>Images</th>
                                            <th>Product Name</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for order_item in object.items.all %}
                                        <tr>
                                            <th scope="row" style="margin-top: 200%;">{{ forloop.counter }}</th>
                                            <td >
                                                <a href="{{ order_item.item.get_absolute_url }}" >
                                                    <img class="rounded" src="{{ order_item.item.image.url }}" alt="" width="200px" height="100px" style="object-fit: cover;"/>
                                                </a>
                                            </td>
                                            <td class="name-pr">
                                                <a href="{{ order_item.item.get_absolute_url }}" style="text-decoration: none;color: #212529;">
                                                <b>{{ order_item.item.title }}</b>
                                        </a>
                                            </td>
                                            <td class="price-pr">
                                                <p>£{{ order_item.item.price|intcomma }}</p>
                                            </td>
                                            <td class="quantity-box">
                                                <div class="row">
                                                    <div class="col-lg-3 col-md-12 col-sm-12">
                                                        <a href="{% url 'shopping:remove_single_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus mr-lg-n2" style="color: teal;"></i></a>
                                                    </div>
                                                    <div class="col-lg-3 col-md-12 col-sm-12">
                                                        {{ order_item.item_quantity }}
                                                    </div>
                                                    <div class="col-lg-3 col-md-12 col-sm-12">
                                                        <a href="{% url 'shopping:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-lg-n2"  style="color: teal;"></i></a>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="total-pr">
                                                <p>£ {{ order_item.get_total_items_price|floatformat:2|intcomma }}</p>
                                            </td>
                                            <td class="remove-pr">
                                                <a href="{% url 'shopping:remove_from_cart' order_item.item.slug %}"  style="color: teal;">
                                            <i class="fas fa-times"></i>
                                        </a>
                                            </td>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan='12' class="text-center"><h4 style="font-family: IM Fell DW Pica SC;">Your cart is empty</h4></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    {% if object.items.all %}
                    <div class="row my-5 ">
                        <div class="col-lg-3 col-sm-12 text-right order-sm-first order-lg-last">
                            <div class="update-box ">
                                <button class="w-100 btn btn-hover float-right" type="submit"><a  data-fancybox-close="" href="{% url 'shopping:product_list' %}" style="text-decoration: none;color: white;">Update Cart</a></button>
                            </div>
                        </div>
                        
                        <div class="col-lg-9  col-sm-12   ">
                            <div class="col-lg-8 col-sm-12"></div>
                            <div class="col-lg-6 col-sm-12">
                                <div class="order-box">
                                    <h3>Order summary</h3>
                                    <div class="d-flex">
                                        {% if object.get_total|floatformat:2|intcomma %} <!-- floatformat:"2g" -->
                                        <h6>Sub Total</h6>
                                        <div class="ml-auto font-weight-bold"> £ {{ object.get_total|floatformat:2|intcomma }} </div>
                                        {% endif %}
                                    </div>
                                    <div class="d-flex">
                                        {% if object.get_total_discount|floatformat:2|intcomma %} 
                                        <h6>Discount</h6>
                                        <div class="ml-auto font-weight-bold"> £ {{ object.get_total_discount|floatformat:2|intcomma }}</div>
                                        {% endif %}
                                    </div>
                                    <hr class="my-1">
                                    <div class="d-flex">
                                        {% if object.get_total_excl_vat|floatformat:2|intcomma %} 
                                        <h6>Total Excl VAT</h6>
                                        <div class="ml-auto font-weight-bold"> £ {{ object.get_total_excl_vat|floatformat:2|intcomma }} </div>
                                        {% endif %}
                                    </div>
                                    <div class="d-flex">
                                        {% if object.get_total_vat|floatformat:2|intcomma %} 
                                        <h6>VAT</h6>
                                        <div class="ml-auto font-weight-bold"> £ {{ object.get_total_vat|floatformat:2|intcomma }}  </div>
                                        {% endif %}
                                    </div>
                                    <div class="d-flex">
                                        {% if object.get_total_shopping_cost|floatformat:2|intcomma %} 
                                        <h6>Shipping Cost</h6>
                                        <div class="ml-auto font-weight-bold"> £ {{ object.get_total_shopping_cost|floatformat:2|intcomma }} </div>
                                        {% endif %}
                                    </div>
                                    <hr>
                                   
                                    <div class="d-flex gr-total">
                                        {% if object.get_grand_total|floatformat:2|intcomma %} 
                                        <h4>Grand Total</h4>
                                        <div class="ml-auto h5"> £ {{ object.get_grand_total|floatformat:2|intcomma }} </div>
                                        {% endif %}
                                    </div>
                                    <hr> 
                                </div>

                                <button class="d-flex w-400 btn btn-hover float-right" type="submit"><a  data-fancybox-close="" href="{% url 'shopping:checkout' %}" style="text-decoration: none;color: white;">Checkout</a></button>
                            </div>    
                        </div>
                    </div>
                    {% else %}
                    <div class="row mt-4">
                        <div class="col-lg-3 col-sm-12 text-right offset-lg-9">
                            <div class="update-box ">
                                <button class="w-100 btn btn-hover float-right" type="submit"><a  data-fancybox-close="" href="{% url 'shopping:product_list' %}" style="text-decoration: none;color: white;">Update Cart</a></button>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        <!-- End Cart -->
    </main>
</div>

<p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>
{% endblock content %}

shopping/templates/shopping/change_form.html
{% extends "admin/change_form.html" %} {% load static %} {% block extrahead %}
{{ block.super }}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
$(function () {
// inspect html to check id of category select dropdown.
$(document).on("change", "select#id_category", function () {
$.getJSON("/getSubcategory/", { id: $(this).val() }, function (j) {
var options = '<option value="">---------</option>';
for (var i = 0; i < j.length; i++) {
options +=
'<option value="' + j[i].id + '">' + j[i].name + "</option>";
}
// inspect html to check id of subcategory select dropdown.
$("select#id_subcategory").html(options);
});
});
});
</script>
{% endblock %}

shopping/templates/shopping/payment.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="wrapper">
    <main data-barba="container" data-barba-namespace='payment'>
        <div class="container mt-3">
            <h1 class="text-center each-page-header" style="font-family: IM Fell DW Pica SC;">PAYMENT</h1>
        </div>
    </main>
</div>
{% endblock content %}

shopping/templates/shopping/product_list.html
{% extends 'lingfield/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="wrapper">
    <main data-barba="container" data-barba-namespace='shopping'>     
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <h1 class="text-left each-page-header" style="font-family: IM Fell DW Pica SC;">SHOP</h1>
                    <p class="text-left  mt-n3" style="color: #3B945E;">Browse all our products</p>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12" style="display: flex;justify-content: end;align-items: center;">
                    <form class="d-inline w-100" action="{% url 'shopping:search' %}" method="get" >
                        <input name="q_shop_product" class="form-control mr-sm-2" type="text" placeholder="Search for Products ..." aria-label="Search" style="font-family: Garamond;background-color:#65CCB8;color: #3B945E;border: none;border-bottom: 1px solid #2C3531;">
                    </form>
                </div>
            </div>

            <br>

            <div class="row">
                <div class="col-lg-3 col-md-12 col-sm-12 py-sm-3 order-lg-2 order-sm-first" >
                   <div class="row" style="border-bottom: 1px solid #182628;border-radius: 5%;">
                        <div class="col-6">
                            <h4 >Categories</h4>
                        </div>
                        <div class="col-6">
                            <p class="text-right"><a href="#" style="color: black;" data-toggle="tooltip" data-placement="right" title="Mode"><i id="showCategory" onclick="showCategories(this)" class="fas fa-angle-up"></i></a></p>
                        </div>
                   </div>
                    <div id="theCategory" style="border-bottom: 2px solid #182628;border-radius: 5%;padding-bottom: 0.3em;">
                        <div  class="list-group list-group-collapse list-group-sm list-group-tree" id="list-group-men" data-children=".sub-men" data-in="fadeInDown" data-out="fadeOutUp">
                            <a href="{% url 'shopping:product_list'  %}" class="list-group-item list-group-item-action"> All Products</a>
                            
                            <div class="list-group-collapse sub-men">
                                {% for c in categories %}
                                <a class="list-group-item list-group-item-action" href="#sub-men1" data-toggle="collapse" aria-expanded="true" aria-controls="sub-men1">{{ c.title }}</a>
                                    {% for subcategory in c.subcategory_set.all %}
                                    <div class="collapse" id="sub-men1" data-parent="#list-group-men">
                                        <div class="list-group">
                                            <a href="{{ subcategory.get_absolute_url }}" class="list-group-item list-group-item-action">{{ subcategory.title }} <small class="text-muted">({{ subcategory.shops.count }})</small></a>
                                        </div>    
                                    </div>
                                    {% endfor %} 
                                {% endfor %}
                            </div>
                         
                        </div>
                       
                    </div>
                   
                </div>
                <div class="col-lg-9 col-md-12 col-sm-12 ">
                    <div class="shop-sorter" style="border-top: 2px solid #182628;border-bottom: 2px solid #182628;border-radius: 5%;padding: 1px 0px 10px 0px;">
                        <div class="row">
                           <div class="col-lg-4 col-md-12 col-sm-12 text-sm-center text-lg-left mt-sm-3">
                                <span class="mr-1 text-sm-center text-lg-left">Sort By</span>
                                    <select class="rounded" style="padding: 8px;background-color: #57BA98;border: #57BA98; color: white;">
                                        <option data-display="Select">All</option>
                                        <option>Most Relevant</option>
                                        <option>Price, Low to High</option>
                                        <option>Price, High to Low</option>
                                        <option>Savings, Low to High</option>
                                        <option>Savings, High to Low</option>
                                    </select>
                           </div>
                           <div class="col-lg-5 col-md-12 col-sm-12 text-sm-center text-lg-center  mt-sm-3">
                                <p class="text-sm-center text-lg-center ">Showing all {{ shop.count }} result(s)</p>
                            </div>
                            <div class="col-lg-3 col-md-12 col-sm-12  text-sm-center text-lg-right  mt-sm-3">
                                <button onclick="gridView()" class="rounded mr-1" style="padding: 4px 6px 4px 6px;background-color: #57BA98;border: #57BA98; color: white;"><i class="fa fa-th-large"></i> </button>
                                <button onclick="listView()" class="rounded" style="padding: 4px 6px 4px 6px;background-color: #57BA98;border: #57BA98; color: white;"><i class="fa fa-bars"></i> </button>
                            </div>
                        </div>
                    </div>

                    <br>
                   
                    <div class="row-shop-view">                             
                        {% for x in shop %}
                        <div class="column-shop-view" style="position: relative;">
                            <a href="{{ x.get_absolute_url }}" style="text-decoration: none;color: white;">
                                <div id="grid-group-img-head">
                                    <img class=" grid-group-img" src="{{ x.image.url }}" width="100%" height="200px" style="object-fit: cover; border-radius: 2px 60px 0px 0px;">
                                </div>
                                <div class="grid-group-text" style="background-color: #65CCB8;padding: 2px 1px 5px 5px;height: 150px;border-radius: 0px 0px  5px 60px;color: #182628"> <!-- #212529 -->
                                    <h4 style="color: #1e4247">{{ x.title }} - <span style="font-size: 20px;"><small>£{{ x.price|intcomma }} <del><small class="ml-1">£{{ x.old_price|intcomma }}</small></del></small></span></h4>
                                    <!-- <h6 class="mt-2" style="color: #1e4247">£{{ x.price|intcomma }} <span class="ml-2"><del><small>£{{ x.old_price|intcomma }}</small></del></span></h6>   -->
                                    {% if user.is_authenticated %}
                                    <a href="{{ x.get_add_to_cart_url }}"  style="padding-right: 15px;position: absolute;bottom: 10px;right: 10px;color: #F2F2F2;text-decoration: none;">Add to Cart</a>
                                    {% else %}
                                    <a href="{% url 'login' %}"  style="padding-right: 15px;position: absolute;bottom: 20px;right: 10px;color: #F2F2F2;text-decoration: none;">Add to Cart</a>
                                    {% endif %}
                                </div>  
                            </a>   
                        </div>
                        {% empty %}
                        <h3>Sorry, item not available. <a href="{% url 'shopping:product_list' %}" style="color: teal;">Click here to continue shopping</a></h3>     
                        {% endfor %}                       
                    </div>

                </div>  

            </div>
        </div>
    </main>
</div>



<p class="text-right fixed-bottom"><a href="#" style="border: 10px solid #182628;background-color: #182628;color: white;"><strong><i class="fas fa-arrow-up"></i></strong></a></p>


<script type="text/javascript"> 

    // document.getElementById('sub-menu1')
    var allnav = document.getElementById("showCategory");

    allnav.onclick = function showCategories() {
        var div = document.getElementById("theCategory");
        if (div.style.display !== 'none') {
            div.style.display = 'none';
            element.classList("fa-angle-down");
            document.getElementById("theCategory").style.height = " ";
        }
        else {
            div.style.display = 'block';
            element.classList.toggle("fa-angle-up");
            document.getElementById("theCategory").style.height = "0";
        }
    };

  

    // Get the elements with class="column"
        var elements = document.getElementsByClassName("column-shop-view");

        // Declare a loop variable
        var i;

        // if (window.matchMedia("(max-width: 700px)").matches) {
        //     /* The viewport is less than, or equal to, 700 pixels wide */
        //     elements[i].style.width = "100%";
        // } else {
        //     /* The viewport is greater than 700 pixels wide */
        //     elements[i].style.width = "50%";
        // }

        // Grid View
        function gridView() {
        for (i = 0; i < elements.length; i++) {
            if (window.matchMedia("(max-width: 600px)").matches) {
                /* The viewport is less than, or equal to, 700 pixels wide */
                elements[i].style.width = "100%";
            } else {
                 /* The viewport is greater than 700 pixels wide */
                elements[i].style.width = "33.33%";
            }
        }
        }
        
        // List View
        function listView() {
        for (i = 0; i < elements.length; i++) {
            elements[i].style.width = "100%";
            
        }
        };

        function showCategories(x) {
        x.classList.toggle("fa-angle-down");
        };

        
</script>
{% endblock content %}